Autom/AC BSA 3 BSA 1
FESAr-SQA/SQA101 pull request #12
Opened 2024-01-16 04:09 UTC by AlanDiCha123

# This branch includes all the automated tesings for all fields with its expecting data
I also would include the automation with Jenkins, but unfortunately it's turned off :(

2024-01-17 14:44 UTC, eduxsan requested changes

2024-01-17 14:44 UTC, eduxsan commented on Pages/edit_customer_page.py
> +    def click_on_login(self):
Please change this name, actual is a little bit misleading

2024-01-17 14:44 UTC, eduxsan commented on Pages/edit_customer_page.py
> +
Missing rest of the fields: Address, City, State, Telephone, Gender, ...

2024-01-17 14:44 UTC, eduxsan commented on Pages/edit_customer_page.py
> +        assert current_data == expected_data, f'El mensaje en el campo {input_name} es {current_data}. Se esperaba {expected_data}'
Please update error message

2024-01-17 14:44 UTC, eduxsan commented on Pages/new_customer_page.py
> +        result_str += '@aol.com'
You can return random email or move this logic on other method, something that allows us to know what is the email we provided for the costumer

2024-01-17 14:44 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +        editCustomer.verify_data_by_field("Customer Name", "Holmes")
Missing validations, as mentioned on previous comment

2024-01-17 14:44 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +        newCustomer.write_date_of_birth("2072000")
Missing select gender

2024-01-18 16:42 UTC, eduxsan approved these changes

2024-01-18 16:45 UTC, LanderoX144 approved these changes

2024-01-18 16:45 UTC, merged