Hice la automatizacion del añadir un user nuevo, me falta la verifica…
FESAr-SQA/SQA101 pull request #13
Opened 2024-01-16 06:45 UTC by LanderoX144

…cion de estos datos en edit

2024-01-17 14:48 UTC, eduxsan requested changes

2024-01-17 14:48 UTC, eduxsan commented on .vscode/launch.json
> +        "test_BSA_1_GLA",
Please revert this change

2024-01-17 14:48 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +
Please remove this empty lines

2024-01-18 17:39 UTC, eduxsan requested changes

2024-01-18 17:39 UTC, eduxsan commented on Pages/new_customer_page.py
> +
Please remove this

2024-01-18 17:39 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +
Please remov ethis

2024-01-18 17:41 UTC, eduxsan approved these changes

2024-01-18 17:47 UTC, AlanDiCha123 requested changes
Check your code

2024-01-18 17:47 UTC, AlanDiCha123 commented on Locators/locators.py
> +        id_customer_reg_msg = (By.XPATH, '//*[@id="customer"]/tbody/tr[4]/td[2]')
Check your identation

2024-01-18 17:47 UTC, AlanDiCha123 commented on Pages/new_customer_page.py
>                  element = self.driver.find_element(*NewCustomerLocators.customer_name_txt)
Where is your "if" statement?

2024-01-18 17:47 UTC, AlanDiCha123 commented on Pages/new_customer_page.py
>          try:
The "except" is missing

2024-01-18 17:47 UTC, AlanDiCha123 commented on Tests/New_Customer/test_new_customer.py
> +from Pages.edit_customer import EditCustomerPage
Import is used twice

2024-01-18 17:48 UTC, AlanDiCha123 commented on Pages/new_customer_page.py
>                  element = self.driver.find_element(*NewCustomerLocators.customer_name_txt)
Sorry

2024-01-18 17:48 UTC, AlanDiCha123 commented on Pages/new_customer_page.py
>          try:
Sorry

2024-01-18 17:49 UTC, AlanDiCha123 commented on Tests/New_Customer/test_new_customer.py
> +from Pages.edit_customer import EditCustomerPage
Sorry

2024-01-18 17:54 UTC, AlanDiCha123 approved these changes
Well done

2024-01-18 17:55 UTC, merged