Finalice la automaticacion BSA-32
FESAr-SQA/SQA101 pull request #17
Opened 2024-01-22 06:16 UTC by LanderoX144

Agregue el test para Automatizar Caso de prueba BSA-32, que consistía en Submit New Customer Form with Duplicate Email
![image](https://github.com/FESAr-SQA/SQA101/assets/142775250/8476fc8b-9ecd-49bc-bbf5-94449ed5e95d)
- se hizo prueba en jenkins y pasó

2024-01-22 14:51 UTC, eduxsan approved these changes
Looks good, just a small change
@AlanDiCha123 please take a look

2024-01-22 14:51 UTC, eduxsan commented on screenshot.png
Please remove this file

2024-01-22 20:50 UTC, AlanDiCha123 approved these changes

2024-01-22 20:50 UTC, AlanDiCha123 commented on screenshot.png
Remove this binary file

2024-01-22 20:53 UTC, AlanDiCha123 requested changes
Check out the binary file

2024-03-09 17:26 UTC, AlanDiCha123 approved these changes

2024-03-09 17:26 UTC, merged