Autom/parameterizacion
FESAr-SQA/SQA101 pull request #5
Opened 2024-01-13 01:37 UTC by AlanDiCha123

## Automation with parameters
This commit parametrizes all the fields in the form for automation

2024-01-13 03:24 UTC, eduxsan requested changes
Looks good for first try. Please take a look at my comments. If you have any questions let me know

2024-01-13 03:24 UTC, eduxsan commented on Locators/locators.py
> +    email_input_message = (By.XPATH, "/html/body/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input")
Take a second lool, probably there's another locators that would be more useful instead of XPath, like NAME or ID

2024-01-13 03:24 UTC, eduxsan commented on Pages/common_page.py
> +            locator = (By.PATH, formated_locator)
Typo here 
```suggestion
            locator = (By.XPATH, formated_locator)
```

2024-01-13 03:24 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +        newCustomer.click_on_input("Customer Name")
Hmm not sure if this is intended lol

2024-01-13 03:24 UTC, eduxsan commented on Tests/New_Customer/test_new_customer.py
> +    def test_new_customer_input_message(self, expected_message):
Missing first parameter `input_name`

2024-01-14 05:14 UTC, AlanDiCha123 commented
Sorry, I don't know what I'm doing lol, I learned that isn't good coding at night

2024-01-14 05:15 UTC, AlanDiCha123 commented
I'll fix it

2024-01-14 05:15 UTC, closed without merging